### ISSUE TITLE
Is it possible to make integration of pug with Blaze?

### ISSUE THREAD

**Issue by ghost** [apatryda/meteor-pug-compiler#1]
Hello! I'm developing on meteor and like using Blaze template engine. Is it possible to integrate Blaze with pug, like there package of integration of Jade with Blaze mquandalle:jade?

Thanks.

**Comment by apatryda** [comment]
Hello,

I really don't know, as my plugin just extends urigo:static-html-compiler,
which in turn was tailored to make it possible to import html files as
strings in javascript, like:

import template from 'xyz.html';

My plugin allows you to do the same with pug templates:

import template from 'xyz.pug';

I didn't get to use blaze, but from what I understand - it handles the
loading of templates on it's own:

"As mentioned in the build system article, the blaze-html-templates package
scans your source code for .html files, picks out <template
name="templateName"> tags, and compiles them into a JavaScript file that
defines a function that implements the component in code, attached to the
Template.templateName symbol."
(
http://blazejs.org/guide/understanding-blaze.html#Blaze-and-the-build-system
 )

It is a different approach.

I couldn't find out if it is possible to create a blaze template from
strings containing html at runtime - if that is possible - my plugin could
be of help to you. If not - it would be easier to modify mquandalle:jade to
handle .pug files, than to use my plugin

Hope I could be of help,
Artur

2017-04-05 5:48 GMT+02:00 Ivan Cherviakov <notifications@github.com>:

**Comment by hems** [comment]
would be amazing to have pug/blaze integration like the jade package!

**Comment by ghost** [comment]
Well it appears that many old meteor packages get abandoned, so unless we try to write one for ourselves hardly anything happen. Thanks anyway.
